# Day 1 of Machine Learning (Numpy sanga kheldai)

In [2]:
import numpy as np
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
a[2]

3

In [5]:
b = np.zeros(2)
print(b)

[0. 0.]


In [6]:
print(a*b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [7]:
c = np.zeros(3)
print(c*a)

[0. 0. 0.]


In [9]:
np.linspace(0,20,num=5)

array([ 0.,  5., 10., 15., 20.])

In [10]:
np.ones(2,dtype=np.int64)

array([1, 1])

# Sorting, concatenation and halka chatak

In [11]:
arr = np.array([35,234,123,12,12,12,1,-1,-99])
np.sort(arr)


array([-99,  -1,   1,  12,  12,  12,  35, 123, 234])

In [13]:
hello = np.concatenate((arr,c))

In [16]:
integer_hello = hello.astype(int)
print(integer_hello)

[ 35 234 123  12  12  12   1  -1 -99   0   0   0]


In [17]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])


In [18]:
array_example.ndim

3

In [19]:
array_example.shape

(3, 2, 4)

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

b = a .reshape(3,2)
b

### Indexing and slicing is same as python list
to make fortran style indexing 
```python
np.reshape(a, newshape=(1, 6), order='F')
```


# How to create an array from existing data

In [29]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])

In [30]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Reshaping and flattening multidimensional arrays


In [33]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a1 = x.flatten()
print(x) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
a2 = x.ravel()
a2[0] = 98
print(x) 
print(a2)


[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
help(ravel)

NameError: name 'ravel' is not defined

In [37]:
help(np.ravel)

Help on _ArrayFunctionDispatcher in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changi